### ISSUE TITLE
CRC Error when installing from board manager

### ISSUE THREAD

**Issue by dsptech** [siwiembedded/siwiduino#1]
Hi, I'm try to install this sdk from the board manager (latest version of Arduino for Windows) but I get a CRC error instead (related to the downloaded packages.). This occur on V. 0.5.0 and 0.7.0.
This is appear the same error of this:
https://github.com/waybyte/logicromsdk/issues/3

I also tested the files downloaded by board manager (arduino_logicrom_v0.7.0.tar.gz and tool-logicromflasher_v2.4.1.tar.gz) by usind 7-zip and it appear that the files are not corrupted. May the CRC error due to an unsupported format on Arduino for windows ?

**Comment by ajaybhargav** [comment]
I tested this on windows release of Arduino 1.8.x 
Did not face any installation issue at all.

**Comment by dsptech** [comment]
I will send you the screen captures. It could be that I'm doing something wrong

**Comment by ajaybhargav** [comment]
If you have downloaded the files manually you may try to run sha256 on it.
The Arduino file should have following if not then probably something is wrong on the file side.
SHA-256:58d36c3b4d34f5fcf15c43fd43442748c61c5c6d8ec00fc835f3f59cceda2e4a

Sha of rest of the file are here in this JSON
https://waybyte.github.io/package_logicrom_index.json

**Comment by dsptech** [comment]
The files are downloaded via the item. I also checked the files by retrieve them from the staging folder. 
I replicated the issue. I attach the capture
![Clipboard01](https://user-images.githubusercontent.com/26789495/147388165-4e6a6a01-3237-4d8d-9ce4-b153c2ab9867.jpg)
![Clipboard02](https://user-images.githubusercontent.com/26789495/147388171-b224de61-a4fb-48a7-85f4-30b211592167.jpg)
![Clipboard03](https://user-images.githubusercontent.com/26789495/147388174-ced32477-f538-41fa-9613-de45e6770286.jpg)
![Clipboard04](https://user-images.githubusercontent.com/26789495/147388177-61e507b7-d361-4033-b1f5-ea988bd7af7e.jpg)
![Clipboard05](https://user-images.githubusercontent.com/26789495/147388178-278e6d9d-8096-43c9-93da-51446720b686.jpg)
s

**Comment by dsptech** [comment]
.. but if I extract (using 7-zip) the file located in C:\Users\Andy\AppData\Local\Arduino15\staging\packages, the extraction will occur with no error. Not I will test the SHA of the downloaded file.

**Comment by ajaybhargav** [comment]
Looks like a common Arduino IDE issue,
Please check some solution mentioned here, they all mentioned deleting staging files and downloading again.
https://github.com/arduino/ArduinoCore-samd/issues/364
And
https://github.com/esp8266/Arduino/issues/630
https://forum.arduino.cc/t/solved-samd-core-crc-doesnt-match/378288

**Comment by dsptech** [comment]
Hi, I can confirm the hash of the downloaded arduino_logicrom_v0.7.0.tar.gz:
58d36c3b4d34f5fcf15c43fd43442748c61c5c6d8ec00fc835f3f59cceda2e4a

Also, the hash of tool-logicromflasher_v2.4.1.tar.gz is:
cfebfdfc10c3ed709fa2b0b0bf95f7cba56a4d748fecb99961d12989d3e6f769

Thanks for your info. I will check it

**Comment by ajaybhargav** [comment]
If you're interested in using Arduino as a framework. I would request you to try PlatformIO once. It much more powerful than Arduino IDE.

**Comment by dsptech** [comment]
Hi, I manually downloaded the files as they are referenced in the json file.

I noticed that the link for the toolchain: https://waybyte.github.io/gcc-arm-none-eabi-8-2018-q4.tar.gz  perform the download of a 134 byte (truncated ?) gzip. I think that this is the issue. Could you try this download ?

My main development IDE is Eclipse and, for Arduino, I use the Sloeber plugin.
My first try is always with the original arduino IDE to make me sure against any compatibilty issue involving Sloeber. 
Anyway, I must admin that I never used Platformio.

**Comment by ajaybhargav** [comment]
Strange, the file is available in repository and it seems to be not being downloaded properly. It might be GitHub issue.
https://github.com/waybyte/waybyte.github.io



> I noticed that the link for the toolchain: https://waybyte.github.io/gcc-arm-none-eabi-8-2018-q4.tar.gz perform the download of a 134 byte (truncated ?) gzip. I think that this is the issue. Could you try this download ?

I downloaded the file and opened as text it has got this

```
version https://git-lfs.github.com/spec/v1
oid sha256:0fefa5c778c25a031b9123fb1e0c5d65c5fc69370fc0b53b27bdf14624f74fbf
size 133110890
```

**Comment by dsptech** [comment]
This link apper to work properly instead:
https://media.githubusercontent.com/media/waybyte/waybyte.github.io/master/gcc-arm-none-eabi-8-2018-q4.tar.gz

**Comment by ajaybhargav** [comment]
I think I need to host it somewhere else.

**Comment by dsptech** [comment]
I manually saved the toolchain in ...\AppData\Local\Arduino15\staging\packages and the package has been installed successfully

**Comment by dsptech** [comment]
Regarding the ... downloaded text I have no useful idea (I don't know github so well)

**Comment by ajaybhargav** [comment]
They probably changed something coz earlier it wasn't like this. Hosted file was downloaded properly. I never had this issue coz toolchain was installed on the system.

**Comment by dsptech** [comment]
I hope that is anyway fixable. 
Now I will take a look to the package.
Thank you for your very fast support. 
Regards.

**Comment by ajaybhargav** [comment]
Thank you for highlighting the issue as I couldn't figure it out myself. Arduino IDE errors were not helpful at all :)

May I ask, Which module are you trying to run it on?

**Comment by dsptech** [comment]
It is a project in the preliminary phase where a GSM/GPRS connection is enough, but everything has to be decided yet. I am currently evaluating the available software libraries.

**Comment by ajaybhargav** [comment]
You may drop me an email ajay.bhargav@waybyte.in with IMEI detail if you want to run logicrom on the module.

**Comment by dsptech** [comment]
ok,
thank you.
I also looked for information on your website, but it appears the site is not working yet.

**Comment by ajaybhargav** [comment]
We are a small startup. Working our way up :) we are working on getting things ready.

**Comment by ajaybhargav** [comment]
Resolved this and https://github.com/waybyte/logicromsdk/issues/3
Thank you!

https://github.com/waybyte/waybyte.github.io/commit/500f50e8a56e71904c61a73ce2eb9e7843ce9d7b
