### ISSUE TITLE
Compiling issue with platfromio Variant.h Not found!

### ISSUE THREAD

**Issue by amir-hg** [siwiembedded/siwiduino#2]
Hi
I want to compile an Arduino empty project by using platformio bu following error appears. Before pasting error let me show my platform.init and main.cpp
--------------------------------------------------------------------------------------------------------------------
my platformio.ini file content:
```

[env:sim868]
platform = logicrom
board = sim868
framework = arduino
```
--------------------------------------------------------------------------------------------------------------------

main.cpp content:

```
#include <Arduino.h>
void setup() {
}

void loop() {
}
```
--------------------------------------------------------------------------------------------------------------------
Logs: 
pio run
Processing sim868 (platform: logicrom; board: sim868; framework: arduino)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/logicrom/sim868.html
PLATFORM: Logicrom Development Platform (0.9.2) > SIMCOM SIM868 GSM Module
HARDWARE: MT2503 260MHz, 94KB RAM, 256KB Flash
PACKAGES: 
 - framework-logicromarduino @ 0.9.1 
 - framework-logicromsdk @ 0.9.4 
 - toolchain-gccarmnoneeabi @ 1.80201.181220 (8.2.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 3 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Compiling .pio/build/sim868/src/main.cpp.o
Archiving .pio/build/sim868/libFrameworkArduinoVariant.a
Indexing .pio/build/sim868/libFrameworkArduinoVariant.a
Compiling .pio/build/sim868/FrameworkArduino/HardwareSerial.cpp.o
Compiling .pio/build/sim868/FrameworkArduino/IPAddress.cpp.o
Compiling .pio/build/sim868/FrameworkArduino/Print.cpp.o
Compiling .pio/build/sim868/FrameworkArduino/Stream.cpp.o
Compiling .pio/build/sim868/FrameworkArduino/WInterrupts.c.o
In file included from /home/amirhg/.platformio/packages/framework-logicromarduino/cores/logicrom/Arduino.h:77,
                 from src/main.cpp:1:
/home/amirhg/.platformio/packages/framework-logicromarduino/cores/logicrom/delay.h:25:10: fatal error: variant.h: No such file or directory

*****************************************************************
* Looking for variant.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:variant.h"
* Web  > https://registry.platformio.org/search?q=header:variant.h
*
*****************************************************************

 #include "variant.h"
          ^~~~~~~~~~~
compilation terminated.
Compiling .pio/build/sim868/FrameworkArduino/WMath.cpp.o
/home/amirhg/.platformio/packages/framework-logicromarduino/cores/logicrom/HardwareSerial.cpp:8:10: fatal error: variant.h: No such file or directory

*****************************************************************
* Looking for variant.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:variant.h"
* Web  > https://registry.platformio.org/search?q=header:variant.h
*
*****************************************************************

 #include <variant.h>
          ^~~~~~~~~~~
compilation terminated.
Compiling .pio/build/sim868/FrameworkArduino/WString.cpp.o
In file included from /home/amirhg/.platformio/packages/framework-logicromarduino/cores/logicrom/Arduino.h:77,
                 from /home/amirhg/.platformio/packages/framework-logicromarduino/cores/logicrom/IPAddress.cpp:20:
/home/amirhg/.platformio/packages/framework-logicromarduino/cores/logicrom/delay.h:25:10: fatal error: variant.h: No such file or directory

*****************************************************************
* Looking for variant.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:variant.h"
* Web  > https://registry.platformio.org/search?q=header:variant.h
*
*****************************************************************

 #include "variant.h"
          ^~~~~~~~~~~
compilation terminated.
Compiling .pio/build/sim868/FrameworkArduino/avr/dtostrf.c.o
In file included from /home/amirhg/.platformio/packages/framework-logicromarduino/cores/logicrom/Arduino.h:77,
                 from /home/amirhg/.platformio/packages/framework-logicromarduino/cores/logicrom/Print.cpp:20:
/home/amirhg/.platformio/packages/framework-logicromarduino/cores/logicrom/delay.h:25:10: fatal error: variant.h: No such file or directory

*****************************************************************
* Looking for variant.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:variant.h"
* Web  > https://registry.platformio.org/search?q=header:variant.h
*
*****************************************************************

 #include "variant.h"
          ^~~~~~~~~~~
compilation terminated.
Compiling .pio/build/sim868/FrameworkArduino/itoa.c.o
In file included from /home/amirhg/.platformio/packages/framework-logicromarduino/cores/logicrom/Arduino.h:77,
                 from /home/amirhg/.platformio/packages/framework-logicromarduino/cores/logicrom/Stream.cpp:25:
/home/amirhg/.platformio/packages/framework-logicromarduino/cores/logicrom/delay.h:25:10: fatal error: variant.h: No such file or directory

*****************************************************************
* Looking for variant.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:variant.h"
* Web  > https://registry.platformio.org/search?q=header:variant.h
*
*****************************************************************

 #include "variant.h"
          ^~~~~~~~~~~
compilation terminated.
In file included from /home/amirhg/.platformio/packages/framework-logicromarduino/cores/logicrom/Arduino.h:77,
                 from /home/amirhg/.platformio/packages/framework-logicromarduino/cores/logicrom/WInterrupts.c:19:
/home/amirhg/.platformio/packages/framework-logicromarduino/cores/logicrom/delay.h:25:10: fatal error: variant.h: No such file or directory

*****************************************************************
* Looking for variant.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:variant.h"
* Web  > https://registry.platformio.org/search?q=header:variant.h
*
*****************************************************************

 #include "variant.h"
          ^~~~~~~~~~~
compilation terminated.
Compiling .pio/build/sim868/FrameworkArduino/main.cpp.o
*** [.pio/build/sim868/src/main.cpp.o] Error 1
*** [.pio/build/sim868/FrameworkArduino/HardwareSerial.cpp.o] Error 1
*** [.pio/build/sim868/FrameworkArduino/IPAddress.cpp.o] Error 1
*** [.pio/build/sim868/FrameworkArduino/Print.cpp.o] Error 1
*** [.pio/build/sim868/FrameworkArduino/Stream.cpp.o] Error 1
*** [.pio/build/sim868/FrameworkArduino/WInterrupts.c.o] Error 1
In file included from /home/amirhg/.platformio/packages/framework-logicromarduino/cores/logicrom/Arduino.h:77,
                 from /home/amirhg/.platformio/packages/framework-logicromarduino/cores/logicrom/main.cpp:23:
/home/amirhg/.platformio/packages/framework-logicromarduino/cores/logicrom/delay.h:25:10: fatal error: variant.h: No such file or directory

*****************************************************************
* Looking for variant.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:variant.h"
* Web  > https://registry.platformio.org/search?q=header:variant.h
*
*****************************************************************

 #include "variant.h"
          ^~~~~~~~~~~
compilation terminated.
*** [.pio/build/sim868/FrameworkArduino/main.cpp.o] Error 1
============================================================================== [FAILED] Took 0.68 seconds ===================================================

**Comment by ajaybhargav** [comment]
Hi Amir,
SIM868 is not added to Arduino framework yet. Mistake is on our side, We will add SIM868 in next release. I will update when it's done.

**Comment by ajaybhargav** [comment]
Support for SIM868 added in v0.9.3
