### ISSUE TITLE
enable to flash OEM firmware after updating with Logicrom firware

### ISSUE THREAD

**Issue by swapniltx** [siwiembedded/siwiduino#6]
I have updated the firmware for EC200U as per document for experimenting with logicrom firmware and system. I am not getting device information on waybyte website. Now I wanted to flash OEM firmware to the same module. I am unable to do so using QFlash or Logicrom flasher.

- With QFlash `Unisoc USB serial port` selected it fails with timeout.
- With Logicrom flasher I do not get option for port.

Can you please suggest a solution or point me towards any document?

**Comment by ajaybhargav** [comment]
> I am not getting device information on waybyte website.

May I know what information are you trying to check? You can email us separately for website related issues.

> Now I wanted to flash OEM firmware to the same module. I am unable to do so using QFlash or Logicrom flasher.

You need to put device in flash mode again. There are two ways to do that:

1. Connect USB_BOOT with VDD_EXT/1.8V
2. Send force boot AT command: AT^FORCEDNLD

You can send at command from serial or USB AT port.

> Can you please suggest a solution or point me towards any document?

We will update our documentation for this topic.

**Comment by swapniltx** [comment]
> Send force boot AT command: AT^FORCEDNLD

this worked for me and I was able to flash OEM firmware. Thank you.

> May I know what information are you trying to check? You can email us separately for website related issues.

I will email you separately for this. Thank you.
